config/routes.rb
Rails.application.routes.draw do

  resources :landings, :users, :sessions

  root 'landings#index'
  get '/about' => 'landings#about'
  get '/brew_finder' => 'landings#brew_finder'

  get '/login' => 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name, :last_name, 
							presence: true

	validates :username,	presence: true,
							uniqueness: { case_sensitive: false }
							
	validates :email, 		presence: true, 
							uniqueness: { case_sensitive: false }, 
							format: { with: EMAIL_REGEX }

	validates :password, 	presence: true, 
							confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(session_params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(session_params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      flash[:login_errors] = "Invalid Login Credentials"
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

  private
  def session_params
  	params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to '/'
  	else
  		render '/users/new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landings/about.html.erb
<div class="container">
	<div class="nav">
		<ul class="nav nav-tabs">
			<li><%= link_to 'Home', root_url %></li>
			<li class="active"><%= link_to 'About <strong>BREW</strong>beacon'.html_safe, about_path %></li>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Profiles</a>
				<ul class="dropdown-menu">
					<li><%= link_to 'About', about_path %></li>
					<li class="divider"></li>
					<li><%= link_to 'Login / Register'.html_safe, login_path %></li>
				</ul>
			</li>
			<li><a href="#">Brew Finder</a></li>
			<li><a href="#">Home Brew</a></li>
		</ul>			
	</div>

	<div class="aboutInfo col-xs-12">
		<dl class="dl-horizontal">
			<dt><h2><%= link_to 'User Profiles', login_path %></h2></dt>
			<dd>Echo Park farm-to-table cliche, ennui Bushwick polaroid raw denim 3 wolf moon kitsch dreamcatcher scenester mixtape. XOXO literally Shoreditch, messenger bag 90's Etsy drinking vinegar Odd Future Neutra sriracha tousled keytar asymmetrical YOLO mlkshk. Tofu Vice bicycle rights pickled meditation beard artisan, hashtag XOXO lomo deep v asymmetrical Shoreditch. Dreamcatcher cred meggings paleo tilde. Vinyl stumptown pug jean shorts. Helvetica Truffaut artisan, irony seitan umami VHS. Health goth fingerstache Shoreditch hoodie, normcore gastropub church-key four dollar toast wolf swag letterpress hella.</dd>
		</dl>
		<dl class="dl-horizontal">
			<dt><h2><a href="#">Brew Finder</a></h2></dt>
			<dd>Echo Park farm-to-table cliche, ennui Bushwick polaroid raw denim 3 wolf moon kitsch dreamcatcher scenester mixtape. XOXO literally Shoreditch, messenger bag 90's Etsy drinking vinegar Odd Future Neutra sriracha tousled keytar asymmetrical YOLO mlkshk. Tofu Vice bicycle rights pickled meditation beard artisan, hashtag XOXO lomo deep v asymmetrical Shoreditch. Dreamcatcher cred meggings paleo tilde. Vinyl stumptown pug jean shorts. Helvetica Truffaut artisan, irony seitan umami VHS. Health goth fingerstache Shoreditch hoodie, normcore gastropub church-key four dollar toast wolf swag letterpress hella.</dd>
		</dl>
		<dl class="dl-horizontal">
			<dt><h2><a href="#">HomeBrew</a></h2></dt>
			<dd>Echo Park farm-to-table cliche, ennui Bushwick polaroid raw denim 3 wolf moon kitsch dreamcatcher scenester mixtape. XOXO literally Shoreditch, messenger bag 90's Etsy drinking vinegar Odd Future Neutra sriracha tousled keytar asymmetrical YOLO mlkshk. Tofu Vice bicycle rights pickled meditation beard artisan, hashtag XOXO lomo deep v asymmetrical Shoreditch. Dreamcatcher cred meggings paleo tilde. Vinyl stumptown pug jean shorts. Helvetica Truffaut artisan, irony seitan umami VHS. Health goth fingerstache Shoreditch hoodie, normcore gastropub church-key four dollar toast wolf swag letterpress hella.</dd>
		</dl>
	</div>

</div>

app/views/landings/brew_finder.html.erb
<div class="container">
	<div class="nav">
		<ul class="nav nav-tabs">
			<li><%= link_to 'Home', root_url %></li>
			<li><%= link_to 'About <strong>BREW</strong>beacon'.html_safe, about_path %></li>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Profiles</a>
				<ul class="dropdown-menu">
					<li><a href="about">About</a></li>
					<li class="divider"></li>
					<li><a href="login">Login / Register</a></li>
				</ul>
			</li>
			<li class="active"><a href="/brew_finder">Brew Finder</a></li>
			<li><a href="#">Home Brew</a></li>
		</ul>			
	</div>
	<div class="finder">
	<!-- CONTROLS -->
		<div class="col-md-4">
			<form>
				<div class="form-group">
					<label for="exampleInputSample1">SAMPLE</label>
					<input type="text" class="form-control" id="exampleInputSample1" placeholder="SAMPLE">
				</div>
				<div class="form-group">
					<label for="exampleInputSample1">SAMPLE</label>
					<input type="text" class="form-control" id="exampleInputSample1" placeholder="SAMPLE">
				</div>
				<div class="checkbox">
					<label>
						<input type="checkbox"> Check 1
					</label>
					<label>
						<input type="checkbox"> Check 2
					</label>
					<label>
						<input type="checkbox"> Check 3
					</label>
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>

		<!-- MAP -->
		<div class="col-md-8">
			<div id="map-canvas"></div>
		</div>
	</div>
</div>
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8Pt23py8j5dn6Elo0EyBnp5jRqHE9glw">
</script>

app/views/landings/index.html.erb
<div class="container">
	<div class="nav">
		<ul class="nav nav-tabs">
			<li class="active"><%= link_to 'Home', root_url %></li>
			<li><%= link_to 'About <strong>BREW</strong>beacon'.html_safe, about_path %></li>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Profiles</a>
				<ul class="dropdown-menu">
					<li><%= link_to 'About', about_path %></li>
					<li class="divider"></li>
					<li><%= link_to 'Login / Register'.html_safe, login_path %></li>
				</ul>
			</li>
			<li><a href="#">Brew Finder</a></li>
			<li><a href="#">Home Brew</a></li>
		</ul>			
	</div>
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			<li data-target="#carousel-example-generic" data-slide-to="3"></li>
			<li data-target="#carousel-example-generic" data-slide-to="4"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active"><%= image_tag('beer1.jpg') %></div>
			<div class="item"><%= image_tag('beer2.jpg') %></div>
			<div class="item"><%= image_tag('beer3.jpg') %></div>
			<div class="item"><%= image_tag('beer4.jpg') %></div>
			<div class="item"><%= image_tag('beer5.jpg') %></div>
		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<h1>Welcome to <strong>BREW</strong>beacon</h1>
	<p>Vinyl flannel mlkshk lumbersexual. Biodiesel put a bird on it cliche, Brooklyn messenger bag blog deep v roof party tilde listicle fingerstache tote bag. Chambray 8-bit keffiyeh chia twee pop-up, single-origin coffee forage tote bag jean shorts messenger bag Vice. Church-key post-ironic meditation tilde. Lumbersexual PBR&B fap, gluten-free bitters hashtag quinoa mixtape flexitarian occupy. Crucifix put a bird on it PBR, Intelligentsia Godard cold-pressed photo booth fashion axe bitters Bushwick readymade kitsch. Pour-over master cleanse stumptown selfies, beard umami Carles farm-to-table mumblecore taxidermy chillwave.</p>

	<p>Single-origin coffee stumptown slow-carb retro banjo artisan irony polaroid. Biodiesel retro stumptown, forage salvia wayfarers heirloom ethical lomo banjo. Put a bird on it kogi cred keytar Vice pug. Mlkshk freegan trust fund, tote bag cold-pressed Odd Future normcore swag mustache. Crucifix whatever lomo, meggings lumbersexual retro butcher jean shorts church-key kitsch banh mi. Before they sold out you probably haven't heard of them Etsy, fashion axe pop-up locavore cray trust fund chambray Bushwick Shoreditch wolf hoodie bitters. Fap Brooklyn tattooed heirloom readymade, narwhal mixtape normcore umami High Life Austin retro freegan.</p>

	<div class="row">
		<div class="col-md-4">
			<div class="thumbnail">
				<%= image_tag('user.png') %>
				<div class="caption">
					<h3>User Profile</h3>
					<p>Craft beer skateboard roof party, Echo Park flannel plaid bitters pork belly selvage health goth kitsch 3 wolf moon. Art party Bushwick Wes Anderson, literally ugh crucifix tofu authentic PBR asymmetrical hella hashtag. McSweeney's bitters plaid Carles flannel. Pitchfork Marfa kale chips Echo Park skateboard migas. Mustache meh seitan taxidermy tofu fap. Fap Banksy Intelligentsia mumblecore tattooed VHS, shabby chic Pinterest biodiesel locavore sartorial High Life 8-bit. Fingerstache Schlitz kogi, tilde skateboard semiotics raw denim disrupt twee vinyl irony tattooed.</p>
					<div class="modal-footer">
						<p><a href="login" class="btn btn-default" role="button"><i class="fa fa-user"></i> Login / Register</a></p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="thumbnail">
				<%= image_tag('map.png') %>
				<div class="caption">
					<h3>Brew Finder</h3>
					<p>Craft beer skateboard roof party, Echo Park flannel plaid bitters pork belly selvage health goth kitsch 3 wolf moon. Art party Bushwick Wes Anderson, literally ugh crucifix tofu authentic PBR asymmetrical hella hashtag. McSweeney's bitters plaid Carles flannel. Pitchfork Marfa kale chips Echo Park skateboard migas. Mustache meh seitan taxidermy tofu fap. Fap Banksy Intelligentsia mumblecore tattooed VHS, shabby chic Pinterest biodiesel locavore sartorial High Life 8-bit. Fingerstache Schlitz kogi, tilde skateboard semiotics raw denim disrupt twee vinyl irony tattooed.</p>
					<div class="modal-footer">
						<p><a href="#" class="btn btn-default" role="button"><i class="fa fa-location-arrow"></i> Find</a></p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="thumbnail">
				<%= image_tag('beer-icon2.png') %>
				<div class="caption">
					<h3>HomeBrew</h3>
					<p>Craft beer skateboard roof party, Echo Park flannel plaid bitters pork belly selvage health goth kitsch 3 wolf moon. Art party Bushwick Wes Anderson, literally ugh crucifix tofu authentic PBR asymmetrical hella hashtag. McSweeney's bitters plaid Carles flannel. Pitchfork Marfa kale chips Echo Park skateboard migas. Mustache meh seitan taxidermy tofu fap. Fap Banksy Intelligentsia mumblecore tattooed VHS, shabby chic Pinterest biodiesel locavore sartorial High Life 8-bit. Fingerstache Schlitz kogi, tilde skateboard semiotics raw denim disrupt twee vinyl irony tattooed.</p>
					<div class="modal-footer">
						<p><a href="#" class="btn btn-default" role="button"><i class="fa fa-beer"></i> Brew Me</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer1"></div>
<div class="footer2">
	<div class="container">
		<div class="col-xs-12 footer2Content">
			
		</div>
		<div class="credits col-xs-12">
			<div class="col-xs-3">
				<p>&copy; Copyright 2015. <strong>BREW</strong>beacon</p>
			</div>
			<div class="col-xs-1 col-xs-offset-8">
				<a id="toTop" href="#top"><i class="fa fa-chevron-circle-up fa-3x"></i></a>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><%= image_tag('beer-icon_sm.png') %></a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown"><%= link_to 'About <strong>BREW</strong>beacon'.html_safe, about_path %></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Profiles</a>
					<ul class="dropdown-menu">
						<li><%= link_to 'About', about_path %></li>
						<li class="divider"></li>
						<li><%= link_to 'Login / Register'.html_safe, login_path %></li>
					</ul>
				</li>
				<li><a href="#">Brew Finder</a></li>
				<li><a href="#">Home Brew</a></li>
			</ul>
		</div>
	</div>
</nav>

<div class="container">
	<div class="row" id="top">
		<div class="header">
			<div class="logo col-sm-9">
				<div class="col-xs-3">
					<%= image_tag('beer-icon.png', size: "125x125") %>
				</div>
				<div class="col-xs-9">
					<h1>BREW<span>beacon</span></h1>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="social pull-right">
					<i class="fa fa-facebook-square fa-2x"></i>
					<i class="fa fa-twitter-square fa-2x"></i>
					<i class="fa fa-instagram fa-2x" data-toggle="tooltip" data-placement="bottom" title="#brewbeacon"></i>
					<i class="fa fa-pinterest-square fa-2x"></i>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BREWBeacon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

	<%= yield %>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
	<div class="nav">
		<ul class="nav nav-tabs">
			<li><%= link_to 'Home', root_url %></li>
			<li><%= link_to 'About <strong>BREW</strong>beacon'.html_safe, about_path %></li>
			<li class="dropdown active">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Profiles</a>
				<ul class="dropdown-menu">
					<li><%= link_to 'About', about_path %></li>
					<li class="divider"></li>
					<li><%= link_to 'Login / Register'.html_safe, login_path %></li>
				</ul>
			</li>
			<li><a href="#">Brew Finder</a></li>
			<li><a href="#">Home Brew</a></li>
		</ul>			
	</div>
	<div class="col-sm-5">
		<h1>Signup!</h1>
		<%= simple_form_for @user, url: '/users' do |f| %>
			<%= f.input :first_name, placeholder: "First Name" %>
			<%= f.input :last_name, placeholder: "Last Name" %>
			<%= f.input :username, placeholder: "Username" %>
			<%= f.input :email, placeholder: "email@email.com" %>
			<%= f.input :password, placeholder: "password" %>
			<%= f.input :password_confirmation, placeholder: "password" %>
			<%= f.button :submit, "Register" %>
		<% end %>
	</div>
	<div class="col-sm-5 col-sm-offset-1">
		<h1>Login!</h1>
		<% if flash.key? ('login_errors') %>
			<div class="list-group">
				<h4 class="list-group-item"><%= flash[:login_errors] %></h4>
			</div>
		<% end %>
		<%= simple_form_for :session, url: '/login' do |f| %>
			<%= f.input :email, placeholder: "email@email.com" %>
			<%= f.input :password, placeholder: "password" %>
			<%= f.button :submit, "Sign in" %>
		<% end %>
	</div>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>